Ignore non-regular files

diff --git a/bin/ods2csv b/bin/ods2csv
--- a/bin/ods2csv
+++ b/bin/ods2csv
@@ -23,6 +23,11 @@ _ods2csv() {
 tempdir="$(mktemp -d)"
 for ods in "$@"
 do
+  if [ ! -f "$1" ]
+  then
+     echo "Error: $1 is not a regular file." 1>&2
+     continue
+  fi
   cp "$1" "$tempdir/"
   (cd "$tempdir" &&
      _ods2csv "$(basename "$1")" &&
diff --git a/bin/odscat b/bin/odscat
--- a/bin/odscat
+++ b/bin/odscat
@@ -27,6 +27,11 @@ _odscat() {
 tempdir="$(mktemp -d)"
 for ods in "$@"
 do
+  if [ ! -f "$1" ]
+  then
+     echo "Error: $1 is not a regular file." 1>&2
+     continue
+  fi
   cp "$1" "$tempdir/"
   (cd "$tempdir" &&
      _odscat "$(basename "$1")" &&
