Do nothing if LibreOffice lives

diff --git a/bin/ods2csv b/bin/ods2csv
--- a/bin/ods2csv
+++ b/bin/ods2csv
@@ -9,6 +9,13 @@ then
   exit 1
 fi
 
+if pgrep soffice >/dev/null
+then
+  echo 'Error: This command cannot work if any other LibreOffice process lives.' 1>&2
+  echo '       Retry after you exit LibreOffice.' 1>&2
+  exit 2
+fi
+
 _ods2csv() {
   soffice --invisible --nofirststartwizard --norestore --headless "$1" macro:///ExportAllToCsv.Module.ExportAllToCsvAndExit 
 }
diff --git a/bin/odscat b/bin/odscat
--- a/bin/odscat
+++ b/bin/odscat
@@ -8,6 +8,13 @@ then
   echo '  odscat /path/to/file.ods ...' 1>&2
 fi
 
+if pgrep soffice >/dev/null
+then
+  echo 'Error: This command cannot work if any other LibreOffice process lives.' 1>&2
+  echo '       Retry after you exit LibreOffice.' 1>&2
+  exit 2
+fi
+
 _odscat() {
   soffice --invisible --nofirststartwizard --norestore --headless "$1" macro:///ExportAllToCsv.Module.ExportAllToCsvAndExit 
   for csv in *.csv
